### ISSUE TITLE
NSFW version?

### ISSUE THREAD

**Issue by TheChuChuTrain** [ninjabunny/KodeNames#11]
Would it be possible for you to add a word list for a NSFW version of the game? :) If not, would you mind if I forked the repo just for the purpose of making a personal version with a NSFW word list?

**Comment by ninjabunny** [comment]
Sorry, no interested in adding those type of words.  You may fork or use the custom list option. Thx

**Comment by sw-tracker** [comment]
I have added them on my branch, feel free to use it.
