### ISSUE TITLE
Seeds generating the same words

### ISSUE THREAD

**Issue by RSeven** [ninjabunny/KodeNames#12]
Using a seed that contains a sequence of repeating patterns generates the exact same game.

For instance:
"aa" and "aaa" generates the same list as "a"
"abab" and "ababab" generates the same list as "ab"
"abcabc" and "abcabcabc" generates the same list as "abc"

**Comment by ninjabunny** [comment]
This is a known bug that the seed library produces. Since it is an edge case and the work around is easy, this is a lib bug that I am not interested in fixing. But thank you for taking the time to point it out to me. Please continue to have a good time with the game.
