### ISSUE TITLE
Official spanish word list

### ISSUE THREAD

**Issue by Qualith** [ninjabunny/KodeNames#13]
As the official set in English differs from the official set in Spanish, the google translator option does not result in the exact match.

May you include this set as an option? Attached is the list of words.

Thank you and congratulations for your nice utility.

[SPANISH_KODENAMES.txt](https://github.com/ninjabunny/KodeNames/files/908069/SPANISH_KODENAMES.txt)

**Comment by sw-tracker** [comment]
Thank you very much for the Spanish word list! I have added it to my branch: https://sw-tracker.github.io/KodeNames/.

Thanks again to ninjabunny!

**Comment by ninjabunny** [comment]
This is useful. Will update in a bit.

**Comment by ninjabunny** [comment]
spanish words added. closing.
