### ISSUE TITLE
Randomly start with red or blue

### ISSUE THREAD

**Issue by Qualith** [ninjabunny/KodeNames#14]
As in the original game, it would be nice to start randomly with red or blue team.

**Comment by sw-tracker** [comment]
This already works on both ninjabunny and my branch. Blue or red will start depending on the seed (randomly). You will see the starting team color as a blue/red line on the left of the page, and the number 9 or 8 will be coloured accordingly.

I have added clarification on the instructions on my branch:
https://github.com/sw-tracker/KodeNames

**Comment by ninjabunny** [comment]
Sw is correct. Closing ticket.
