### ISSUE TITLE
Spanish word set problems

### ISSUE THREAD

**Issue by Qualith** [ninjabunny/KodeNames#15]
I have checked and it seems that there are some problems with the Spanish word set.

I have a look at data.js and I think that the word list is truncated, "sable" is the last correct word, the rest of the word list is absent.
There is a problem too with some special Spanish characters, for example "pingüino", "revolución", "caña" are not correctly written. Perhaps it is an issue related to unicode conversion....

**Comment by Qualith** [comment]
Sw-tracker fork has it right, by the way...

**Comment by ninjabunny** [comment]
Ok. Lemme go copy it from sw ;)

**Comment by ninjabunny** [comment]
Thanks for the heads up. should be ok now. :D
