### ISSUE TITLE
Undo spymaster click / toggle green?

### ISSUE THREAD

**Issue by klausw** [ninjabunny/KodeNames#20]
It's fairly easy to accidentally click the wrong square as spymaster, and there seems to be no easy way to undo its green color other than resetting and redoing all the green squares from scratch.

Would it make sense to make the "clicked" method act as a toggle in spy master mode, so that a second click turns it from green back to its original red/blue/gray color? 

At first glance, this should fit with the current click method here: https://github.com/ninjabunny/KodeNames/blob/master/scripts/index.js#L130

**Comment by ninjabunny** [comment]
Sounds reasonable. Wanna do a pr?
