### ISSUE TITLE
Words in French

### ISSUE THREAD

**Issue by roulio2** [ninjabunny/KodeNames#27]
Hi,
Thanks a lot for offering me the possibility to play Codenames with my friends during the lockdown. I have not tested it yet, but it seems great!
Before playing I decided to copy all the words of the French game. Here they are: https://docs.google.com/document/d/1b4047Q2zs8l1BnFfrWY2HKXSPd66l-BgkqkH8HxTfw8/edit?usp=sharing
Perhaps you could integrate them in the game?
Thanks once more.

**Comment by ninjabunny** [comment]
Is the Google translate feature not accurate enough?

**Comment by roulio2** [comment]
No, not really. Sometimes the results are strange.
For instance, in English, very often verbs and nouns are the same word, which is not the case in French. Hence sometimes when the word should be translated as a noun it is translated (sometimes in the imperative form) as a verb (for example "drop" becomes "let it go").
And I think the translators of the game made efforts to find words that have several meaning in French, I think you kind of loose that with the Google translation of English words.

So it could work, but I think the result would be better with actual French words. I saw the words in Spanish so I thought you would accept other languages. But if you don't, that's alright, I will you the "custom words" instead.

**Comment by ninjabunny** [comment]
That's reasonable.  Ill try to get to it today.  I'll close the issue when
I'm done.  You need to do a hard refresh to see the result.

**Comment by roulio2** [comment]
Thank you very much! I didn't expect it to be so quick ;-)

If you receive more and more translation, you could imagine having the language selected by default depending on the person's browser options.

**Comment by ninjabunny** [comment]
merged.
I understand that I can automate the language selection, but the analytics show that there are not enough users from those countries to warrant the time to do it. 
please feel free to make a pull request if you would like to add that feature. Thanks for playing!

**Comment by roulio2** [comment]
Thanks that works fine!
Just I noticed, seed 348 there is the word "B" which is not a French word, and if I'm not mistaken it's not in my list.
I'm not a developer, so I can't pull the request, but that's fine, that's really minor.
Another possibility would be (I don't know if it's possible), that the last choices are "saved" when we come back to the site (the confirm check box, the word set). But again, that's not important, the game is perfect as is!
Thanks for the proactivity ;-) I'll consider a donation

**Comment by roulio2** [comment]
I found "CH" which is also not a word... (seed 1989) Strange there must have been mistakes in the copied list.

Here it is:

ŒIL BRANCHE BOMBE PLATEAU RAME CHARGE ASILE LENTILLE NAIN MODE DROIT VASE CANARD VAMPIRE MEMBRE LIGNE SATELLITE KANGOUROU REINE BOUTEILLE FUITE FORMULE ROSE PILOTE ROI CHANCE LIVRE POISSON COCHON VERRE POLICE DANSE PILE ESPACE MAIN JOUR BALANCE ÉCLAIR PIED JOURNAL PÉTROLE NEIGE TIMBRE COUPE PAILLE FACTEUR CRITIQUE VAGUE BALLE PARACHUTE CAFÉ TÊTE RAT PÔLE MENU COUVERTURE GAUCHE RÈGLE ZÉRO CENTRE BOÎTE RAIE PAGE UNIFORME PIANO CEINTURE MIEL SERPENT REMISE SARDINE BANQUE POMME NUMÉRO MOUSSE CHIEN ROBE BALLON SOLDAT PATRON AMPOULE CHAÎNE BOTTE PRISE AIR CITROUILLE BALEINE PHYSIQUE AVOCAT CAMEMBERT FRANÇAIS DRAGON AMOUR TOKYO GRÈCE MAGIE AVION POIRE BOULET BŒUF EAU ROULETTE DINOSAURE COLLE FILET FRONT ROULEAU MEUBLE FIGURE MALADIE TRÉSOR VIN RUSSIE BÊTE IRIS ENTRÉE MINE GRAIN ROND POUCE BATEAU ROBOT CHOCOLAT LANGUE PALME FRAISE MANCHE PÊCHE BASE GUERRE VOLEUR CHEVALIER CROCHET KIWI ÉTUDE SIRÈNE B TON CARREAU LOUCHE CHEMISE SOL ÉCOLE LAIT ALLEMAGNE SCHTROUMPF HÉROS PINGOUIN OPÉRA GÉNIE RÉSISTANCE ÉGYPTE LIEN POINT FOU NUIT CHARME VOLUME AFRIQUE BAGUETTE TENNIS OISEAU MARS ESPRIT ARGENT NŒUD CLÉ SOMME ÉTOILE TABLE TABLEAU APPAREIL CINÉMA FLÛTE POÊLE PARTIE ATOUT BARRE TROU CLASSE LICORNE POISON ATLANTIQUE ÉGALITÉ SOLEIL BOUCHE CAMPAGNE JET VAISSEAU TUILE MAÎTRESSE ŒUF ROME RÉVOLUTION MARCHE PERLE ANNEAU SOURIS COURANT NOIR CODE BLÉ CHOU SOLUTION PENDULE DON DOCTEUR VOITURE CLUB CABINET LETTRE MARRON TOUR CHAMP PIGEON ANGLETERRE CAFARD ARC POMPE FIN TEMPS RESTAURANT MOUCHE PLACE PESTE FORT CARRIÈRE PORTABLE LIQUIDE BON HERBE OR TRAIT CUISINE BOURSE QUARTIER CH TEAU REQUIN BRETELLE POSTE RELIGIEUSE BUREAU BOUCHON MACHINE PLANCHE OPÉRATION COMMERCE TALON COURSE ORANGE GRUE ENCEINTE CARTON MOULE BANC GUIDE RECETTE SIÈGE MORT BÛCHE CANON PLAT JUMELLES FANTÔME SCÈNE ANGE BAR PLAN FEUILLE GORGE COURONNE CARTE PRINCESSE BIÈRE HISTOIRE JEU LONDRES NINJA CYCLE FARCE NEW-YORK APLES ROUGE CORDE GARDE GEL CHEVAL VENT CHAMPAGNE CHINE MINEUR CORNE HOLLYWOOD EUROPE ÉCHELLE HIVER CANADA LUXE BANDE PALAIS PRÊT RAYON CELLULE TAMBOUR DROITE CŒUR ESSENCE CADRE TUBE LIT FOYER QUEUE PYRAMIDE CHAUSSON TITRE CARTOUCHE LION PAPIER PIRATE MICROSCOPE FER COURT VISION PIÈCE ASTÉRIX LUMIÈRE ESPION PLUME PLAGE VERT MARQUE PLANTE MÉMOIRE MANÈGE RADIO BUT PENSÉE BAIE FORÊT MARIN CHEF VOL HÔPITAL CHASSE COQ ESPAGNE BERLIN INDIEN MAJEUR SENS PASSE CANNE BRIQUE GRENADE TERRE LASER CHAT CERCLE BOUTON BOUGIE ALIEN SORCIÈRE VISAGE SCIENCE FEU CHAPEAU SORTIE LUNETTES NAPOLÉON AUSTRALIE ARAIGNÉE AILE CASINO NOËL FERME GLACE PARIS HIMALAYA VOILE ENSEMBLE BANANE PHARE CIRQUE MILLIONNAIRE MOUSTACHE LUNE SEPT AIGUILLE ORDRE COL COUTEAU TOILE ÉPONGE NOTE JUNGLE HÔTEL COTON TEMPLE GÉANT VIE MOLIÈRE AMÉRIQUE

**Comment by ninjabunny** [comment]
b and ch are removed.
for user preference persistence... sorry, i think the work is not worth the # of users are using the feature.

**Comment by roulio2** [comment]
Thanks! And fair enough ;-)

**Comment by roulio2** [comment]
I think I understood where the "B" and "CH" problems came from. For some reason the "Â" letter didn't pass. So the words "BÂTON" and "CHÂTEAU" didn't appear and instead we have "B", "TON", "CH" and "TEAU". Can you please delete these four and add "BATON" and "CHATEAU" (without the accents, its fine)?
Thanks again and sorry for the troubles.

**Comment by ninjabunny** [comment]
np. fixed. have fun!

**Comment by roulio2** [comment]
Sweet! I'll definitely have!
