### ISSUE TITLE
Request being able to use different delimiters or upload custom words from a file

### ISSUE THREAD

**Issue by ryerrabelli** [ninjabunny/KodeNames#34]
This app is really cool, and I absolutely love it. I want to start using the custom word set more often. One feature that would be nice is to either be able to use a different delimiter (for example semicolon or comma instead of space). Alternatively, you could create a way to upload the custom words from a CSV files. This would allow me to include some short phrases to go along with the words, as well as have include words from a special genre (for example medical words or history words)

**Comment by ninjabunny** [comment]
delimiting by comma is actually a good idea... i think i can do that really
quickly but i dont think i will offer file upload feature.

**Comment by ninjabunny** [comment]
implemented
