### ISSUE TITLE
Suggestion - seed without spymaster view

### ISSUE THREAD

**Issue by DesignChapman** [ninjabunny/KodeNames#6]
Would it be possible to have a main seeded game generate a link/seed to the same 25 word grid but with the 'I am Spymaster' button hidden, ideally in a way that obscures the original seed. 

Not a necessary feature by any means, but would assist games when not played locally.

Sorry if this isn't the appropriate place, or an infeasible feature.

**Comment by ninjabunny** [comment]
This is feasible, however, I am unsure what it adds to the game. It seems like this feature request is about preventing cheating and I am not interested. Cheaters will cheat, I dont play with cheaters. Let me know If I had misunderstood you.

**Comment by DesignChapman** [comment]
You hit the nail on the head,

You're also right in saying that it doesn't change anything for cheaters,
because they could still cheat by clicking on every word on their own
screen.
