### ISSUE TITLE
Remaining word count is not correct when switching start team

### ISSUE THREAD

**Issue by ig-ealbert** [ninjabunny/KodeNames#7]
1. Start a new game in which red goes first.
   Note that the words remaining are correct - 9 for red and 8 for blue.
2. Start a new game in which blue goes first.
   Note that the words remaining are incorrect - there should be 9 for blue and 8 for red, but it is the other way around.

We love playing this for team building at work.  We often play 2 or 3 games in a row which is how we found this bug.  Whenever blue goes first, the words remaining counts are wrong.

**Comment by ig-ealbert** [comment]
In updateScore() it seems to always subtract from blue.

```
//subtract 1 for non-starting team
    if($('.redStarts') === 1){
        redScore--;
    } else {
        blueScore--;
    }
```

**Comment by ninjabunny** [comment]
fixed: https://github.com/ninjabunny/KodeNames/commit/97d46b417b04d63402c10026232e2d06d0648677

@ig-ealbert where do you work? are they hiring? I will play codenames with you hahaha :D

**Comment by ig-ealbert** [comment]
@ninjabunny I work at Infragistics.  We have job openings listed [here](http://www.infragistics.com/about-us/careers).  We'd be happy to play with you! ^_^
Thanks for fixing this so quickly!  Should I verify and close the issue?

**Comment by ninjabunny** [comment]
Yes. Thanks!

**Comment by ig-ealbert** [comment]
Verified!
